sudo: required

services:
  - docker

# to install docker compose (not working correctly with curl)
language: python

python:
  - "3.5"

env:
  DOCKER_COMPOSE_VERSION: 1.10.0

install:
  - pip install -U docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose


script:
  - docker-compose up -d

